# Generated by Django 5.2.6 on 2026-10-09 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_last4'),
        ('transactions', '0003_fraud_detection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='tx_user_created_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & dining'), ('SHOPPING', 'Shopping'), ('TRAVEL', 'Travel'), ('BILLS', 'Bills & utilities'), ('HEALTHCARE', 'Healthcare'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at', '-id'], name='tx_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status', '-created_at'], name='tx_user_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'amount'], name='tx_user_amount_idx'),
        ),
    ]
