# Generated by Django 5.2.6 on 2026-10-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_rbac_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last4',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
